/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ApiMempoolRouteImport } from './routes/api/mempool'
import { Route as ApiWeeklyBriefRouteImport } from './routes/api/weekly-brief'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMempoolRoute = ApiMempoolRouteImport.update({
  id: '/api/mempool',
  path: '/api/mempool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeeklyBriefRoute = ApiWeeklyBriefRouteImport.update({
  id: '/api/weekly-brief',
  path: '/api/weekly-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/api/mempool': typeof ApiMempoolRoute
  '/api/weekly-brief': typeof ApiWeeklyBriefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/api/mempool': typeof ApiMempoolRoute
  '/api/weekly-brief': typeof ApiWeeklyBriefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/api/mempool': typeof ApiMempoolRoute
  '/api/weekly-brief': typeof ApiWeeklyBriefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/news' | '/api/mempool' | '/api/weekly-brief' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/news' | '/api/mempool' | '/api/weekly-brief' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/news'
    | '/api/mempool'
    | '/api/weekly-brief'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRoute
  ApiMempoolRoute: typeof ApiMempoolRoute
  ApiWeeklyBriefRoute: typeof ApiWeeklyBriefRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mempool': {
      id: '/api/mempool'
      path: '/api/mempool'
      fullPath: '/api/mempool'
      preLoaderRoute: typeof ApiMempoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekly-brief': {
      id: '/api/weekly-brief'
      path: '/api/weekly-brief'
      fullPath: '/api/weekly-brief'
      preLoaderRoute: typeof ApiWeeklyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRoute,
  ApiMempoolRoute: ApiMempoolRoute,
  ApiWeeklyBriefRoute: ApiWeeklyBriefRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
